global using IconifyBundle;
global using IconifyBundle.Generator;
global using TUnit.Core;
global using TUnit.Assertions;
global using TUnit.Assertions.Extensions;
global using System.IO.Compression;
global using System.Text.Json;
global using System.Text.RegularExpressions;
global using Replicant;
global using static VerifyTUnit.Verifier;
