//HintName: Feather.Registration.g.cs
// <auto-generated/>
#nullable enable
namespace IconifyBundle;

static class FeatherRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Initialize()
    {
        global::IconifyBundle.IconRegistry.RegisterPath("feather", "activity", global::System.IO.Path.Combine(global::System.AppContext.BaseDirectory, "iconifybundle", "feather", "activity.svg"), 24, 24);
    }
}
