//HintName: Feather.Paths.g.cs
// <auto-generated/>
#nullable enable
namespace Iconistic;

static class FeatherPathExtensions
{
    extension(global::Iconistic.Feather)
    {
        public static string ActivityPath => global::Iconistic.Feather.PathOf("activity");
        public static string AlertCirclePath => global::Iconistic.Feather.PathOf("alert-circle");
        public static string _1passwordPath => global::Iconistic.Feather.PathOf("1password");
    }
}
