//HintName: Feather.Paths.g.cs
// <auto-generated/>
#nullable enable
namespace IconifyBundle;

static class FeatherPathExtensions
{
    extension(global::IconifyBundle.Feather)
    {
        public static string ActivityPath => global::IconifyBundle.Feather.PathOf("activity");
        public static string AlertCirclePath => global::IconifyBundle.Feather.PathOf("alert-circle");
        public static string _1passwordPath => global::IconifyBundle.Feather.PathOf("1password");
    }
}
