//HintName: Feather.Registration.g.cs
// <auto-generated/>
#nullable enable
namespace IconifyBundle;

static class FeatherRegistration
{
    [global::System.Runtime.CompilerServices.ModuleInitializer]
    internal static void Initialize()
    {
        global::IconifyBundle.IconRegistry.Register("feather", "activity", "<path d=\"M12 2v20\"/>", 24, 24);
    }
}
