<?xml version="1.0" encoding="utf-8"?>
<Project>

  <PropertyGroup>
    <LangVersion>preview</LangVersion>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
    <Papyrine_SponsorshipExemption>OpenSource</Papyrine_SponsorshipExemption>
    <Papyrine_SponsorshipExemptionUntil>2027-08</Papyrine_SponsorshipExemptionUntil>
    <Verify_SponsorshipExemption>OpenSource</Verify_SponsorshipExemption>
    <Verify_SponsorshipExemptionUntil>2027-08</Verify_SponsorshipExemptionUntil>
  </PropertyGroup>

</Project>
