namespace Iconistic.Generator;

public static class Emitter
{
    public static string Emit(Manifest manifest, bool diskMode)
    {
        var builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n");
        builder.Append("#nullable enable\n");
        builder.Append("namespace Iconistic;\n\n");
        builder.Append("/// <summary>Strongly typed access to the <c>").Append(manifest.Prefix).Append("</c> Iconify pack.</summary>\n");
        builder.Append("public static partial class ").Append(manifest.ClassName).Append('\n');
        builder.Append("{\n");
        builder.Append("    static readonly global::Iconistic.IconPack pack =\n");
        builder.Append("        global::Iconistic.IconPack.ForAssembly(typeof(global::")
            .Append(manifest.MarkerType)
            .Append(").Assembly, \"")
            .Append(manifest.Prefix)
            .Append("\");\n\n");

        var used = new HashSet<string>(StringComparer.Ordinal) { "pack" };
        foreach (var name in manifest.IconNames)
        {
            var candidate = IdentifierNaming.ToPascalCase(name);
            if (candidate == manifest.ClassName)
            {
                // A member cannot share the name of its enclosing type (CS0542).
                candidate += "Icon";
            }

            var member = IdentifierNaming.Deduplicate(candidate, used);
            var literal = Escape(name);
            builder.Append("    /// <summary>The <c>").Append(manifest.Prefix).Append(':').Append(name).Append("</c> icon.</summary>\n");
            builder.Append("    public static global::Iconistic.Icon ").Append(member).Append(" => pack[\"").Append(literal).Append("\"];\n");

            if (diskMode)
            {
                var pathMember = IdentifierNaming.Deduplicate(member + "Path", used);
                builder.Append("    /// <summary>The on-disk path of the <c>").Append(manifest.Prefix).Append(':').Append(name).Append("</c> icon.</summary>\n");
                builder.Append("    public static string ").Append(pathMember).Append(" => pack.PathOf(\"").Append(literal).Append("\");\n");
            }
        }

        builder.Append("}\n");
        return builder.ToString();
    }

    static string Escape(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
