using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;

namespace Iconistic.Generator;

/// <summary>
/// Builds the generated <c>Icons</c> source for all declared packs, writing DeployedFile packs to
/// disk and accumulating diagnostics.
/// </summary>
static class SourceEmitter
{
    public static string Emit(IReadOnlyList<PackSpec> packs, Settings settings, List<Diagnostic> diagnostics)
    {
        var rootNamespace = string.IsNullOrWhiteSpace(settings.RootNamespace)
            ? "Iconistic.Generated"
            : settings.RootNamespace;

        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated/>");
        builder.AppendLine("#nullable enable");
        builder.AppendLine("#pragma warning disable");
        builder.AppendLine();
        builder.AppendLine($"namespace {rootNamespace};");
        builder.AppendLine();
        builder.AppendLine("/// <summary>Strongly typed Iconify icons, generated by Iconistic.</summary>");
        builder.AppendLine("public static partial class Icons");
        builder.AppendLine("{");

        var deployed = new List<(string ClassName, string FileName)>();
        var usedClassNames = new HashSet<string>(StringComparer.Ordinal);

        foreach (var pack in packs)
        {
            EmitPack(builder, pack, settings, diagnostics, usedClassNames, deployed);
        }

        if (deployed.Count > 0)
        {
            EmitInitialize(builder, deployed);
        }

        builder.AppendLine("}");
        return builder.ToString();
    }

    static void EmitPack(
        StringBuilder builder,
        PackSpec pack,
        Settings settings,
        List<Diagnostic> diagnostics,
        HashSet<string> usedClassNames,
        List<(string ClassName, string FileName)> deployed)
    {
        var icons = pack.Icons.ToArray();
        if (icons.Length == 0)
        {
            diagnostics.Add(Diagnostic.Create(Diagnostics.EmptyPack, Location.None, pack.Prefix));
            return;
        }

        var rawJson = IconifyDownloader.GetRawJson(pack.Prefix, icons, settings, out var error);
        if (rawJson is null)
        {
            diagnostics.Add(error == "offline"
                ? Diagnostic.Create(Diagnostics.Offline, Location.None, pack.Prefix)
                : Diagnostic.Create(Diagnostics.DownloadFailed, Location.None, pack.Prefix, error));
            return;
        }

        Dictionary<string, object?> root;
        try
        {
            root = MiniJson.Parse(rawJson) as Dictionary<string, object?>
                   ?? throw new FormatException("response was not a JSON object");
        }
        catch (Exception exception)
        {
            diagnostics.Add(Diagnostic.Create(Diagnostics.DownloadFailed, Location.None, pack.Prefix, exception.Message));
            return;
        }

        var (found, notFound, defaultWidth, defaultHeight) = IconResolver.Resolve(root, icons);
        if (notFound.Count > 0)
        {
            diagnostics.Add(Diagnostic.Create(
                Diagnostics.IconNotFound, Location.None, pack.Prefix, string.Join(", ", notFound)));
        }

        if (found.Count == 0)
        {
            return;
        }

        var className = NameMangler.ToUniqueIdentifier(pack.Prefix, usedClassNames);
        var usedMembers = new HashSet<string>(StringComparer.Ordinal);

        builder.AppendLine($"    /// <summary>Icons from the Iconify '{pack.Prefix}' collection.</summary>");
        builder.AppendLine($"    public static partial class {className}");
        builder.AppendLine("    {");

        switch (pack.Storage)
        {
            case Storage.BakedIn:
                EmitBaked(builder, found, usedMembers);
                break;
            case Storage.EmbeddedResource:
                EmitEmbedded(builder, found, defaultWidth, defaultHeight, usedMembers);
                break;
            case Storage.DeployedFile:
                EmitDeployed(builder, pack, found, defaultWidth, defaultHeight, settings, usedMembers, deployed, className);
                break;
        }

        builder.AppendLine("    }");
        builder.AppendLine();
    }

    static void EmitBaked(
        StringBuilder builder,
        List<KeyValuePair<string, NormIcon>> found,
        HashSet<string> usedMembers)
    {
        foreach (var pair in found)
        {
            var member = NameMangler.ToUniqueIdentifier(pair.Key, usedMembers);
            var icon = pair.Value;
            var body = SymbolDisplay.FormatLiteral(icon.Body, quote: true);

            string args;
            if (icon is { Left: 0, Top: 0, Rotate: 0, HFlip: false, VFlip: false })
            {
                args = $"{body}, {icon.Width}, {icon.Height}";
            }
            else
            {
                args = $"{body}, {icon.Width}, {icon.Height}, {icon.Left}, {icon.Top}, {icon.Rotate}, {Bool(icon.HFlip)}, {Bool(icon.VFlip)}";
            }

            builder.AppendLine($"        /// <summary>The '{pair.Key}' icon.</summary>");
            builder.AppendLine($"        public static global::Iconistic.IconisticIcon {member} => new({args});");
        }
    }

    static void EmitEmbedded(
        StringBuilder builder,
        List<KeyValuePair<string, NormIcon>> found,
        int defaultWidth,
        int defaultHeight,
        HashSet<string> usedMembers)
    {
        var json = CompactJsonWriter.Write(defaultWidth, defaultHeight, found);
        var literal = SymbolDisplay.FormatLiteral(json, quote: true);
        builder.AppendLine($"        static readonly global::Iconistic.IconPack pack = new({literal});");

        foreach (var pair in found)
        {
            var member = NameMangler.ToUniqueIdentifier(pair.Key, usedMembers);
            var name = SymbolDisplay.FormatLiteral(pair.Key, quote: true);
            builder.AppendLine($"        /// <summary>The '{pair.Key}' icon.</summary>");
            builder.AppendLine($"        public static global::Iconistic.IconisticIcon {member} => pack[{name}];");
        }
    }

    static void EmitDeployed(
        StringBuilder builder,
        PackSpec pack,
        List<KeyValuePair<string, NormIcon>> found,
        int defaultWidth,
        int defaultHeight,
        Settings settings,
        HashSet<string> usedMembers,
        List<(string ClassName, string FileName)> deployed,
        string className)
    {
        var json = CompactJsonWriter.Write(defaultWidth, defaultHeight, found);
        var fileName = SanitizeFileName(pack.Prefix) + ".json";
        WriteDeployedFile(settings.DeployDirectory, fileName, json);
        deployed.Add((className, fileName));

        builder.AppendLine("        /// <summary>The deployed pack, populated by Icons.InitializeAsync.</summary>");
        builder.AppendLine("        public static readonly global::Iconistic.IconPack Pack = new();");
        builder.AppendLine($"        /// <summary>The deployed file name, served from the deploy directory.</summary>");
        builder.AppendLine($"        public const string DeployedFileName = {SymbolDisplay.FormatLiteral(fileName, quote: true)};");

        foreach (var pair in found)
        {
            var member = NameMangler.ToUniqueIdentifier(pair.Key, usedMembers);
            var name = SymbolDisplay.FormatLiteral(pair.Key, quote: true);
            builder.AppendLine($"        /// <summary>The '{pair.Key}' icon.</summary>");
            builder.AppendLine($"        public static global::Iconistic.IconisticIcon {member} => Pack[{name}];");
        }
    }

    static void EmitInitialize(StringBuilder builder, List<(string ClassName, string FileName)> deployed)
    {
        builder.AppendLine("    /// <summary>Loads all DeployedFile packs. Call once at startup, e.g. in Blazor Program.cs.</summary>");
        builder.AppendLine("    public static async global::System.Threading.Tasks.Task InitializeAsync(global::System.Net.Http.HttpClient client, string basePath = \"iconistic\")");
        builder.AppendLine("    {");
        builder.AppendLine("        var prefix = string.IsNullOrEmpty(basePath) ? \"\" : basePath.TrimEnd('/') + \"/\";");
        foreach (var (className, fileName) in deployed)
        {
            var name = SymbolDisplay.FormatLiteral(fileName, quote: true);
            builder.AppendLine($"        await global::Iconistic.IconPackLoader.LoadAsync({className}.Pack, client, prefix + {name});");
        }

        builder.AppendLine("    }");
        builder.AppendLine();
    }

    static void WriteDeployedFile(string deployDirectory, string fileName, string json)
    {
        try
        {
            Directory.CreateDirectory(deployDirectory);
            var path = Path.Combine(deployDirectory, fileName);
            if (!File.Exists(path) || File.ReadAllText(path) != json)
            {
                File.WriteAllText(path, json);
            }
        }
        catch
        {
            // Writing the deployed asset is best-effort; the typed API still compiles.
        }
    }

    static string SanitizeFileName(string value)
    {
        var builder = new StringBuilder(value.Length);
        foreach (var c in value)
        {
            builder.Append(char.IsLetterOrDigit(c) || c is '-' or '_' ? c : '_');
        }

        return builder.Length == 0 ? "pack" : builder.ToString();
    }

    static string Bool(bool value) => value ? "true" : "false";
}
