using System.Globalization;

namespace IconifyBundle.Generator;

public static class Emitter
{
    // The (icon-name, member-name) pairs. Used by the pack class (compiled at pack time), the path
    // extensions, and usage detection so member names line up exactly everywhere.
    public static List<(string IconName, string Member)> Members(Manifest manifest)
    {
        var used = new HashSet<string>(StringComparer.Ordinal) { "pack", "PathOf" };
        var result = new List<(string, string)>();
        foreach (var name in manifest.IconNames)
        {
            var candidate = IdentifierNaming.ToPascalCase(name);
            if (candidate == manifest.ClassName)
            {
                // A member cannot share the name of its enclosing type (CS0542).
                candidate += "Icon";
            }

            result.Add((name, IdentifierNaming.Deduplicate(candidate, used)));
        }

        return result;
    }

    // The (icon-name, path-member-name) pairs, e.g. ("activity", "ActivityPath"). Mirrors the dedup used
    // by EmitPathExtensions so detection and emission agree.
    public static List<(string IconName, string Member)> PathMembers(Manifest manifest)
    {
        var members = Members(manifest);
        var used = new HashSet<string>(StringComparer.Ordinal) { "pack", "PathOf" };
        foreach (var (_, member) in members)
        {
            used.Add(member);
        }

        var result = new List<(string, string)>();
        foreach (var (name, member) in members)
        {
            result.Add((name, IdentifierNaming.Deduplicate(member + "Path", used)));
        }

        return result;
    }

    /// <summary>
    /// The strongly-typed pack class, compiled into the <c>IconifyBundle.&lt;Pack&gt;</c> assembly at pack
    /// time. It carries no icon data; members resolve through the runtime <c>IconRegistry</c>, which the
    /// consumer's generated module initializer populates with the used icons.
    /// </summary>
    public static string EmitPackClass(Manifest manifest)
    {
        var builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n");
        builder.Append("#nullable enable\n");
        builder.Append("namespace IconifyBundle;\n\n");
        builder.Append("/// <summary>Strongly typed access to the <c>").Append(manifest.Prefix).Append("</c> Iconify pack.</summary>\n");
        builder.Append("[global::IconifyBundle.IconifyPack(\"").Append(Literal(manifest.Prefix)).Append("\")]\n");
        builder.Append("public static class ").Append(manifest.ClassName).Append('\n');
        builder.Append("{\n");
        // Fully-qualified Icon/IconPack: an icon named "icon"/"icon-pack" generates a member that would
        // otherwise shadow an unqualified type name and break compilation (CS0118).
        builder.Append("    static readonly global::IconifyBundle.IconPack pack =\n");
        builder.Append("        global::IconifyBundle.IconPack.ForPrefix(\"").Append(Literal(manifest.Prefix)).Append("\");\n\n");

        // No per-member XML doc comments: packs build with GenerateDocumentationFile=false (so docs are
        // never emitted), and for the largest packs the comments double the source size and compile time.
        foreach (var (name, member) in Members(manifest))
        {
            builder.Append("    public static global::IconifyBundle.Icon ").Append(member).Append(" => pack[\"").Append(Literal(name)).Append("\"];\n");
        }

        builder.Append("\n    /// <summary>The on-disk path of the named icon (present only in Disk mode, for materialised icons).</summary>\n");
        builder.Append("    public static string PathOf(string name) => pack.PathOf(name);\n");
        builder.Append("}\n");
        return builder.ToString();
    }

    /// <summary>
    /// Static extension properties giving a strongly-typed path per icon (e.g. <c>Feather.ActivityPath</c>),
    /// generated in the consumer in Disk mode. Emitted for every icon so any can be referenced; only the
    /// icons actually referenced are written to the build output.
    /// </summary>
    public static string EmitPathExtensions(Manifest manifest)
    {
        var builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n");
        builder.Append("#nullable enable\n");
        builder.Append("namespace IconifyBundle;\n\n");
        builder.Append("static class ").Append(manifest.ClassName).Append("PathExtensions\n");
        builder.Append("{\n");
        builder.Append("    extension(global::IconifyBundle.").Append(manifest.ClassName).Append(")\n");
        builder.Append("    {\n");
        foreach (var (name, pathMember) in PathMembers(manifest))
        {
            builder.Append("        public static string ").Append(pathMember)
                .Append(" => global::IconifyBundle.").Append(manifest.ClassName).Append(".PathOf(\"").Append(Literal(name)).Append("\");\n");
        }

        builder.Append("    }\n");
        builder.Append("}\n");
        return builder.ToString();
    }

    /// <summary>
    /// Resource mode: a <c>[ModuleInitializer]</c> that bakes the used icons' bodies into the consuming
    /// assembly by registering them inline.
    /// </summary>
    public static string EmitResourceRegistration(Manifest manifest, IEnumerable<string> usedIconNames)
    {
        var builder = StartRegistration(manifest);
        foreach (var name in usedIconNames)
        {
            if (!manifest.Data.TryGetValue(name, out var data))
            {
                continue;
            }

            builder.Append("        global::IconifyBundle.IconRegistry.Register(\"")
                .Append(Literal(manifest.Prefix)).Append("\", \"")
                .Append(Literal(name)).Append("\", \"")
                .Append(Literal(data.Body)).Append("\", ")
                .Append(Num(data.Width)).Append(", ").Append(Num(data.Height)).Append(");\n");
        }

        return EndRegistration(builder);
    }

    /// <summary>
    /// Disk mode: a <c>[ModuleInitializer]</c> that registers the used icons' on-disk paths (the build
    /// copies the matching <c>.svg</c> files to the output directory).
    /// </summary>
    public static string EmitDiskRegistration(Manifest manifest, IEnumerable<string> usedIconNames)
    {
        var builder = StartRegistration(manifest);
        foreach (var name in usedIconNames)
        {
            if (!manifest.Data.TryGetValue(name, out var data))
            {
                continue;
            }

            builder.Append("        global::IconifyBundle.IconRegistry.RegisterPath(\"")
                .Append(Literal(manifest.Prefix)).Append("\", \"")
                .Append(Literal(name)).Append("\", global::System.IO.Path.Combine(global::System.AppContext.BaseDirectory, \"iconifybundle\", \"")
                .Append(Literal(manifest.Prefix)).Append("\", \"")
                .Append(Literal(name)).Append(".svg\"), ")
                .Append(Num(data.Width)).Append(", ").Append(Num(data.Height)).Append(");\n");
        }

        return EndRegistration(builder);
    }

    /// <summary>
    /// Disk mode: a (compile-inert) source file listing the used icon names, which the pack's build target
    /// reads to copy the matching <c>.svg</c> files to output. The names sit inside a <c>#if false</c>
    /// region so they need not be valid C#; the target ignores lines starting with <c>/</c> or <c>#</c>.
    /// </summary>
    public static string EmitUsedList(Manifest manifest, IEnumerable<string> usedIconNames)
    {
        var builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n");
        builder.Append("#if false // IconifyBundle used icons for pack '").Append(manifest.Prefix).Append("'\n");
        foreach (var name in usedIconNames)
        {
            builder.Append(name).Append('\n');
        }

        builder.Append("#endif\n");
        return builder.ToString();
    }

    static StringBuilder StartRegistration(Manifest manifest)
    {
        var builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n");
        builder.Append("#nullable enable\n");
        builder.Append("namespace IconifyBundle;\n\n");
        builder.Append("static class ").Append(manifest.ClassName).Append("Registration\n");
        builder.Append("{\n");
        builder.Append("    [global::System.Runtime.CompilerServices.ModuleInitializer]\n");
        builder.Append("    internal static void Initialize()\n");
        builder.Append("    {\n");
        return builder;
    }

    static string EndRegistration(StringBuilder builder)
    {
        builder.Append("    }\n");
        builder.Append("}\n");
        return builder.ToString();
    }

    static string Num(double value) => value.ToString(CultureInfo.InvariantCulture);

    static string Literal(string value) =>
        value
            .Replace("\\", "\\\\")
            .Replace("\"", "\\\"")
            .Replace("\r", "\\r")
            .Replace("\n", "\\n")
            .Replace("\t", "\\t");
}
