namespace IconifyBundle.Generator;

public static class Emitter
{
    // The (icon-name, member-name) pairs. Used by both the pack class (compiled at pack time) and the
    // path extensions (generated in the consumer) so member names line up exactly.
    static List<(string IconName, string Member)> Members(Manifest manifest)
    {
        var used = new HashSet<string>(StringComparer.Ordinal) { "pack", "PathOf" };
        var result = new List<(string, string)>();
        foreach (var name in manifest.IconNames)
        {
            var candidate = IdentifierNaming.ToPascalCase(name);
            if (candidate == manifest.ClassName)
            {
                // A member cannot share the name of its enclosing type (CS0542).
                candidate += "Icon";
            }

            result.Add((name, IdentifierNaming.Deduplicate(candidate, used)));
        }

        return result;
    }

    /// <summary>
    /// The strongly-typed pack class, compiled into the <c>IconifyBundle.&lt;Pack&gt;</c> assembly at pack time.
    /// </summary>
    public static string EmitPackClass(Manifest manifest)
    {
        var builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n");
        builder.Append("#nullable enable\n");
        builder.Append("namespace IconifyBundle;\n\n");
        builder.Append("/// <summary>Strongly typed access to the <c>").Append(manifest.Prefix).Append("</c> Iconify pack.</summary>\n");
        builder.Append("public static class ").Append(manifest.ClassName).Append('\n');
        builder.Append("{\n");
        // Fully-qualified Icon/IconPack: an icon named "icon"/"icon-pack" generates a member that would
        // otherwise shadow an unqualified type name and break compilation (CS0118).
        builder.Append("    static readonly global::IconifyBundle.IconPack pack =\n");
        builder.Append("        global::IconifyBundle.IconPack.ForAssembly(typeof(")
            .Append(manifest.ClassName)
            .Append(").Assembly, \"")
            .Append(manifest.Prefix)
            .Append("\");\n\n");

        // No per-member XML doc comments: packs build with GenerateDocumentationFile=false (so docs are
        // never emitted), and for the largest packs the comments double the source size and compile time.
        foreach (var (name, member) in Members(manifest))
        {
            builder.Append("    public static global::IconifyBundle.Icon ").Append(member).Append(" => pack[\"").Append(Escape(name)).Append("\"];\n");
        }

        builder.Append("\n    /// <summary>The on-disk path of the named icon (present only when the consumer set <c>IconifyBundleExtractDisk</c>).</summary>\n");
        builder.Append("    public static string PathOf(string name) => pack.PathOf(name);\n");
        builder.Append("}\n");
        return builder.ToString();
    }

    /// <summary>
    /// Static extension properties giving a strongly-typed path per icon (e.g. <c>Feather.ActivityPath</c>),
    /// generated in the consumer only when <c>IconifyBundleExtractDisk</c> is set.
    /// </summary>
    public static string EmitPathExtensions(Manifest manifest)
    {
        var members = Members(manifest);
        var used = new HashSet<string>(StringComparer.Ordinal) { "pack", "PathOf" };
        foreach (var (_, member) in members)
        {
            used.Add(member);
        }

        var builder = new StringBuilder();
        builder.Append("// <auto-generated/>\n");
        builder.Append("#nullable enable\n");
        builder.Append("namespace IconifyBundle;\n\n");
        builder.Append("static class ").Append(manifest.ClassName).Append("PathExtensions\n");
        builder.Append("{\n");
        builder.Append("    extension(global::IconifyBundle.").Append(manifest.ClassName).Append(")\n");
        builder.Append("    {\n");
        foreach (var (name, member) in members)
        {
            var pathMember = IdentifierNaming.Deduplicate(member + "Path", used);
            builder.Append("        public static string ").Append(pathMember)
                .Append(" => global::IconifyBundle.").Append(manifest.ClassName).Append(".PathOf(\"").Append(Escape(name)).Append("\");\n");
        }

        builder.Append("    }\n");
        builder.Append("}\n");
        return builder.ToString();
    }

    static string Escape(string value) =>
        value.Replace("\\", "\\\\").Replace("\"", "\\\"");
}
